Libraries

```{r}

library(sf)
library(dplyr)
library(classInt)
library(tmap)

setwd('C:\\Users\\Taylor\\My Drive\\School\\01 Current Semester\\R\\06 Final Project')

```

Cleveland Data

```{r}

# load data

cleveland <- st_read("C:\\Users\\Taylor\\My Drive\\School\\01 Current Semester\\R\\06 Final Project\\Combined_Parcels_-_Cleveland_Only\\Combined_Parcels_-_Cleveland_Only.shp")

# filter data

cleveland <- dplyr::select(cleveland, c('certifie_3', 'total_acre', 'geometry'))

# calculate tax productivity

cleveland$tax_prod <- with(cleveland, certifie_3/total_acre) 

# remove NA's, then inf's and 0's

cleveland <- cleveland %>%
             filter(!is.na(tax_prod)) %>%
             filter(!is.infinite(tax_prod)) %>%
             filter(tax_prod != 0)

# (from classInt library) create classification breaks

cleveland.breaks <- classIntervals(cleveland$tax_prod, n = 5, style = "fisher")

# add column to Cleveland data set using classification breaks

cleveland <- cleveland %>% mutate(percent_class = cut(tax_prod, cleveland.breaks$brks, include.lowest = T))

```

Cleveland map

```{r}

cleveland.map <- tm_shape(cleveland) +
                          tm_fill(col = 'tax_prod',
                                  style = 'fisher',
                                  palette = 'Greens', 
                                  border.alpha = 0,
                                  title = '$/Acre') +
                          tm_layout(main.title = 'Tax Productivity per Acre ($)',
                                    main.title.size = 1,
                                    frame = F,
                                    legend.outside = T,
                                    legend.outside.position = 'left') +
                          tmap_options(check.and.fix = T)

cleveland.map

```

Columbus Data

```{r}

# load data

columbus <- st_read("C:\\Users\\Taylor\\My Drive\\School\\01 Current Semester\\R\\06 Final Project\\Parcel_Boundaries\\Parcel_Boundaries.shp")

# filter out non columbus metro parcels

columbus <- columbus %>% filter (columbus$CVTTXDSCRP == 'CITY OF COLUMBUS')

# filter data

columbus <- dplyr::select(columbus, c('TOTCNTTXOD','ACRES','geometry'))

# calculate tax productivity

columbus$tax_prod <- with(columbus, TOTCNTTXOD/ACRES) 

# remove NA's, then inf's and 0's

columbus <- columbus %>%
             filter(!is.na(tax_prod)) %>%
             filter(!is.infinite(tax_prod)) %>%
             filter(tax_prod != 0)

# (from classInt library) create classification breaks

columbus.breaks <- classIntervals(columbus$tax_prod, n = 5, style = "fisher")

# add column to Cleveland data set using classification breaks

columbus <- columbus %>% mutate(percent_class = cut(tax_prod, columbus.breaks$brks, include.lowest = T))

```

Columbus Map

```{r}

columbus.map <- tm_shape(columbus) +
                          tm_fill(col = 'tax_prod',
                                  palette = 'Greens',
                                  style = 'fisher',
                                  border.alpha = 0,
                                  title = '$/Acre') +
                          tm_layout(main.title = 'Tax Productivity per Acre ($)',
                                    main.title.size = 1,
                                    frame = F,
                                    legend.outside = T,
                                    legend.outside.position = 'left') +
                          tmap_options(check.and.fix = T)

columbus.map

```

Cincinnati Data

```{r}

#load data

cincinnati <- st_read('C:\\Users\\Taylor\\My Drive\\School\\01 Current Semester\\R\\06 Final Project\\cincinnati_parcels\\cincinnati_parcels.shp')

#filter data

####cincinnati <- cincinnati %>% filter (cincinnati$CVTTXDSCRP == 'CITY OF COLUMBUS')

# filter data

cincinnati <- dplyr::select(cincinnati, c('ANNUAL_TAX','ACREDEED','geometry'))

# calculate tax productivity

cincinnati$tax_prod <- with(cincinnati, ANNUAL_TAX/ACREDEED) 

# remove NA's, then inf's and 0's

cincinnati <- cincinnati %>%
             filter(!is.na(tax_prod)) %>%
             filter(!is.infinite(tax_prod)) %>%
             filter(tax_prod != 0)

# (from classInt library) create classification breaks

cincinnati.breaks <- classIntervals(cincinnati$tax_prod, n = 5, style = "fisher")

# add column to Cleveland data set using classification breaks

cincinnati <- cincinnati %>% mutate(percent_class = cut(tax_prod, cincinnati.breaks$brks, include.lowest = T))

```

Cincinnati Map

```{r}

cincinnati.map <- tm_shape(cincinnati) +
                          tm_fill(col = 'tax_prod',
                                  palette = 'Greens',
                                  style = 'fisher',
                                  border.alpha = 0,
                                  title = '$/Acre') +
                          tm_layout(main.title = 'Tax Productivity per Acre ($)',
                                    main.title.size = 1,
                                    frame = F,
                                    legend.outside = T,
                                    legend.outside.position = 'left') +
                          tmap_options(check.and.fix = T)

cincinnati.map

```
Third plot comparing statistics

```{r}

#average parcel size

cleveland.parcel.sum <- rowSums(certifie_3)

cleveland.average.size <- cleveland.parcel.sum/133045

#total tax income

```


Analysis

```{r}

tmap_arrange(cleveland.map, columbus.map, cincinnati.map)

```
